if (ReportData.find().count() === 0) {
ReportData.insert({
    inserteddate: new Date(),
    reporttype: "KPITree",
    location: "UK",
    period: 2,    
    market: "Tesco",
    header: "KPI Chart",
    PERIOD_NO:"2014P02",
    COUNTRY:"UK",
    PERIOD_GROUP:"PERIOD 201409",
    EPOS_SALES_TY:"£2942M",
    CC_SALES_TY:"£2069M",
    CC_CUSTOMERS_TY:"14M",
    CC_SPV_TY:"£26",
    CC_UPV_TY:15,
    CC_SPU_TY:"£1.7",
    CC_SPC_TY:"£152",
    CC_VPC_TY:6,
    EPOS_SALES_YOY:"0.6%",
    CC_SALES_YOY:"-0.6%",
    CC_CUSTOMERS_YOY:"-0.5%",
    CC_SPV_YOY:"0.9%",
    CC_UPV_YOY:"-3.6%",
    CC_SPU_YOY:"4.7%",
    CC_SPC_YOY:"-0.1%",
    CC_VPC_YOY:"-1%",
    EPOS_SALES_CONTRIB:"£18M",
    CC_SALES_CONTRIB:"-£12M",
    CC_CUSTOMERS_CONTRIB:"-£10M",
    CC_SPV_CONTRIB:"£18M",
    CC_UPV_CONTRIB:"-£77M",
    CC_SPU_CONTRIB:"£95M",
    CC_SPC_CONTRIB:"-£2M",
    CC_VPC_CONTRIB:"-£20M",
    NON_CC_TY:"£873M",
    NON_CC_YOY:"3.6%",
    NON_CC_CONTRIB:"£31M",
narrations: [
    {header: "How did Tesco perform last period?", paragraph: "Total Sales has increased by 0.6% vs last year in 2014P02.<br>Also performance in 2014P02 is better than last period.<br>Non Clubcard Sales grew by 3.6% in 2014P02 indicating that customers are swiping less often vs last year.<br>Clubcard Sales in 2014P02 has deccreased by (0.6%) vs last year.<br>Decline in Units per Basket is the biggest driver of underformance in 2014P02.<br>In 2014P02 we also saw decline in Visit per Customer.<br>However we have also observed growth in Average Price per Unit."},
    {header: "Which Customer groups influenced the change the most?", paragraph: "UP-MARKET customers sales declined by 1.3% which contributed most to the overall sales decline. The decline in sales from UP-MARKET customers is mainly due to decrease in Units per Basket vs last year.<br>However MID MARKET Customers has shown positive growth of (1.1%)."},
    {header: "Which Store groups were impacted the most?", paragraph: "Biggest decline in Clubcard Sales came from METRO stores of (6.1%) which is mostly attributed to decline in Units per Basket.<br>However SUPER STORE stores has shown positive growth of 0.1%."},
    {header: "Which Categories were impacted the most?", paragraph: "BBT and PRODUCE saw the largest Clubcard Sales decline at (7.3%) and (6.7%) driven by decline in Customer penetration and Average Price per Unit respectively.<br>Compared to last period PRODUCE has seen improved performance however BBT has done worst."}
]
  });
ReportData.insert(  {
    inserteddate: new Date(),
    reporttype: "KPITree",
    location: "UK",
    period: 3,    
    market: "Tesco",
    header: "KPI Chart",
    PERIOD_NO:"2014P03",
    COUNTRY:"UK",
    PERIOD_GROUP:"PERIOD 201413",
    EPOS_SALES_TY:"£2895M",
    CC_SALES_TY:"£2021M",
    CC_CUSTOMERS_TY:"14M",
    CC_SPV_TY:"£25",
    CC_UPV_TY:15,
    CC_SPU_TY:"£1.7",
    CC_SPC_TY:"£148",
    CC_VPC_TY:6,
    EPOS_SALES_YOY:"-5.4%",
    CC_SALES_YOY:"-7.1%",
    CC_CUSTOMERS_YOY:"-1.8%",
    CC_SPV_YOY:"-2.6%",
    CC_UPV_YOY:"-3.6%",
    CC_SPU_YOY:"1%",
    CC_SPC_YOY:"-5.4%",
    CC_VPC_YOY:"-2.9%",
    EPOS_SALES_CONTRIB:"-£165M",
    CC_SALES_CONTRIB:"-£154M",
    CC_CUSTOMERS_CONTRIB:"-£37M",
    CC_SPV_CONTRIB:"-£55M",
    CC_UPV_CONTRIB:"-£76M",
    CC_SPU_CONTRIB:"£21M",
    CC_SPC_CONTRIB:"-£116M",
    CC_VPC_CONTRIB:"-£62M",
    NON_CC_TY:"£874M",
    NON_CC_YOY:"-1.3%",
    NON_CC_CONTRIB:"-£11M",
narrations: [
    {header: "How did Tesco perform last period?", paragraph: "Total Sales has increased by 0.6% vs last year in 2014P02.<br>Also performance in 2014P02 is better than last period.<br>Non Clubcard Sales grew by 3.6% in 2014P02 indicating that customers are swiping less often vs last year.<br>Clubcard Sales in 2014P02 has deccreased by (0.6%) vs last year.<br>decline in Units per Basket is the biggest driver of underformance in 2014P02.<br>In 2014P02 we also saw decline in Visit per Customer.<br>However we have also observed growth in Average Price per Unit."},
    {header: "Which Customer groups influenced the change the most?", paragraph: "UP-MARKET customers sales declined by 1.3% which contributed most to the overall sales decline. The decline in sales from UP-MARKET customers is mainly due to decrease in Units per Basket vs last year.<br>However MID MARKET Customers has shown positive growth of (1.1%)."},
    {header: "Which Store groups were impacted the most?", paragraph: "Biggest decline in Clubcard Sales came from METRO stores of (6.1%) which is mostly attributed to decline in Units per Basket.<br>However SUPER STORE stores has shown positive growth of 0.1%."},
    {header: "Which Categories were impacted the most?", paragraph: "BBT and PRODUCE saw the largest Clubcard Sales decline at (7.3%) and (6.7%) driven by decline in Customer penetration and Average Price per Unit respectively.<br>Compared to last period PRODUCE has seen improved performance however BBT has done worst."}
]
  });
ReportData.insert(  {
    inserteddate: new Date(),
    reporttype: "KPITree",
    location: "UK",
    period: 4,    
    market: "Tesco",
    header: "KPI Chart",    
    PERIOD_NO:"2014P04",
    COUNTRY:"UK",
    PERIOD_GROUP:"PERIOD 201418",
    EPOS_SALES_TY:"£3659M",
    CC_SALES_TY:"£2529M",
    CC_CUSTOMERS_TY:"14M",
    CC_SPV_TY:"£25",
    CC_UPV_TY:15,
    CC_SPU_TY:"£1.7",
    CC_SPC_TY:"£178",
    CC_VPC_TY:7,
    EPOS_SALES_YOY:"-5.2%",
    CC_SALES_YOY:"-6.9%",
    CC_CUSTOMERS_YOY:"-1.6%",
    CC_SPV_YOY:"-3.1%",
    CC_UPV_YOY:"-4.1%",
    CC_SPU_YOY:"1.1%",
    CC_SPC_YOY:"-5.4%",
    CC_VPC_YOY:"-2.3%",
    EPOS_SALES_CONTRIB:"-£201M",
    CC_SALES_CONTRIB:"-£187M",
    CC_CUSTOMERS_CONTRIB:"-£43M",
    CC_SPV_CONTRIB:"-£83M",
    CC_UPV_CONTRIB:"-£111M",
    CC_SPU_CONTRIB:"£28M",
    CC_SPC_CONTRIB:"-£144M",
    CC_VPC_CONTRIB:"-£62M",
    NON_CC_TY:"£1130M",
    NON_CC_YOY:"-1.2%",
    NON_CC_CONTRIB:"-£14M",
narrations: [
    {header: "How did Tesco perform last period?", paragraph: "Total Sales has decreased by (5.4%) vs last year in 2014P03.<br>Also the performance in 2014P03 has gone down compared to last period.<br>Non Clubcard Sales declined by (1.3%) in 2014P03 which also contributed towards the overall decline.<br>Clubcard Sales in 2014P03 has deccreased by (7.1%) vs last year.<br>decline in Units per Basket is the biggest driver of underformance in 2014P03.<br>In 2014P03 we also saw decline in Visit per Customer.<br>However we have also observed growth in Average Price per Unit."},
    {header: "Which Customer groups influenced the change the most?", paragraph: "UP-MARKET customers sales declined by (5.3%) which contributed most to the overall sales decline. The decline in sales from UP-MARKET customers is mainly due to decrease in Visit per Customer vs last year.<br>However LESS AFFLUENT Customers has shown positive growth of (8%)."},
    {header: "Which Store groups were impacted the most?", paragraph: "Biggest decline in Clubcard Sales came from METRO stores of (7.9%) which is mostly attributed to decline in Total Tesco Shoppers.<br>However EXPRESS stores has shown positive growth of (5.88%)."},
    {header: "Which Categories were impacted the most?", paragraph: "MFPE and PRODUCE saw the largest Clubcard Sales decline at (10.1%) and (10%) driven by decline in Customer penetration and Average Price per Unit respectively.<br>Compared to last period both MFPE and PRODUCE has done worst."}
]
  });
ReportData.insert(  {
    inserteddate: new Date(),
    reporttype: "KPITree",
    location: "UK",
    period: 5,    
    market: "Tesco",
    header: "KPI Chart",    
    PERIOD_NO:"2014P05",
    COUNTRY:"UK",
    PERIOD_GROUP:"PERIOD 201422",
    EPOS_SALES_TY:"£2918M",
    CC_SALES_TY:"£1999M",
    CC_CUSTOMERS_TY:"14M",
    CC_SPV_TY:"£25",
    CC_UPV_TY:15,
    CC_SPU_TY:"£1.7",
    CC_SPC_TY:"£147",
    CC_VPC_TY:6,
    EPOS_SALES_YOY:"-6.5%",
    CC_SALES_YOY:"-7.6%",
    CC_CUSTOMERS_YOY:"-2%",
    CC_SPV_YOY:"-2.5%",
    CC_UPV_YOY:"-4.2%",
    CC_SPU_YOY:"1.7%",
    CC_SPC_YOY:"-5.7%",
    CC_VPC_YOY:"-3.2%",
    EPOS_SALES_CONTRIB:"-£203M",
    CC_SALES_CONTRIB:"-£163M",
    CC_CUSTOMERS_CONTRIB:"-£42M",
    CC_SPV_CONTRIB:"-£53M",
    CC_UPV_CONTRIB:"-£89M",
    CC_SPU_CONTRIB:"£35M",
    CC_SPC_CONTRIB:"-£122M",
    CC_VPC_CONTRIB:"-£68M",
    NON_CC_TY:"£919M",
    NON_CC_YOY:"-4.2%",
    NON_CC_CONTRIB:"-£40M",
narrations: [
    {header: "How did Tesco perform last period?", paragraph: "Total Sales has decreased by (5.2%) vs last year in 2014P04.<br>We have observed similar performance compared to last period.<br>Non Clubcard Sales declined by (1.2%) in 2014P04 which also contributed towards the overall decline.<br>Clubcard Sales in 2014P04 has deccreased by (6.9%) vs last year.<br>decline in Units per Basket is the biggest driver of underformance in 2014P04.<br>In 2014P04 we also saw decline in Visit per Customer.<br>However we have also observed growth in Average Price per Unit."},
    {header: "Which Customer groups influenced the change the most?", paragraph: "UP-MARKET customers sales declined by (5.1%) which contributed most to the overall sales decline. The decline in sales from UP-MARKET customers is mainly due to decrease in Units per Basket vs last year.<br>However MID MARKET Customers has shown positive growth of (7.3%)."},
    {header: "Which Store groups were impacted the most?", paragraph: "Biggest decline in Clubcard Sales came from METRO stores of (8.2%) which is mostly attributed to decline in Units per Basket.<br>However EXPRESS stores has shown positive growth of (5.9%)."},
    {header: "Which Categories were impacted the most?", paragraph: "PRODUCE and MFPE saw the largest Clubcard Sales decline at (11.1%) and (10.4%) driven by decline in Average Price per Unit and Customer penetration respectively.<br>Compared to last period both PRODUCE and MFPE has done worst."}
]
  });
ReportData.insert(  {
    inserteddate: new Date(),
    reporttype: "KPITree",
    location: "UK",
    period: 6,    
    market: "Tesco",
    header: "KPI Chart",    
    PERIOD_NO:"2014P06",
    COUNTRY:"UK",
    PERIOD_GROUP:"PERIOD 201426",
    EPOS_SALES_TY:"£2828M",
    CC_SALES_TY:"£1930M",
    CC_CUSTOMERS_TY:"14M",
    CC_SPV_TY:"£25",
    CC_UPV_TY:15,
    CC_SPU_TY:"£1.7",
    CC_SPC_TY:"£143",
    CC_VPC_TY:6,
    EPOS_SALES_YOY:"-6.1%",
    CC_SALES_YOY:"-7.9%",
    CC_CUSTOMERS_YOY:"-2%",
    CC_SPV_YOY:"-4.2%",
    CC_UPV_YOY:"-4.9%",
    CC_SPU_YOY:"0.7%",
    CC_SPC_YOY:"-6%",
    CC_VPC_YOY:"-1.9%",
    EPOS_SALES_CONTRIB:"-£183M",
    CC_SALES_CONTRIB:"-£165M",
    CC_CUSTOMERS_CONTRIB:"-£40M",
    CC_SPV_CONTRIB:"-£87M",
    CC_UPV_CONTRIB:"-£101M",
    CC_SPU_CONTRIB:"£14M",
    CC_SPC_CONTRIB:"-£125M",
    CC_VPC_CONTRIB:"-£38M",
    NON_CC_TY:"£897M",
    NON_CC_YOY:"-2%",
    NON_CC_CONTRIB:"-£18M",
narrations: [
    {header: "How did Tesco perform last period?", paragraph: "Total Sales has decreased by (6.5%) vs last year in 2014P05.<br>Also the performance in 2014P05 has gone down compared to last period.<br>Non Clubcard Sales declined by (4.2%) in 2014P05 which also contributed towards the overall decline.<br>Clubcard Sales in 2014P05 has deccreased by (7.6%) vs last year.<br>decline in Units per Basket is the biggest driver of underformance in 2014P05.<br>In 2014P05 we also saw decline in Visit per Customer.<br>However we have also observed growth in Average Price per Unit."},
    {header: "Which Customer groups influenced the change the most?", paragraph: "UP-MARKET customers sales declined by (6.4%) which contributed most to the overall sales decline. The decline in sales from UP-MARKET customers is mainly due to decrease in Visit per Customer vs last year.<br>However MID MARKET Customers has shown positive growth of (7.9%)."},
    {header: "Which Store groups were impacted the most?", paragraph: "Biggest decline in Clubcard Sales came from METRO stores of (7.8%) which is mostly attributed to decline in Total Tesco Shoppers.<br>However EXPRESS stores has shown positive growth of (7.4%)."},
    {header: "Which Categories were impacted the most?", paragraph: "PRODUCE and BWS saw the largest Clubcard Sales decline at (13.5%) and (9.9%) driven by decline in Average Price per Unit and Customer penetration respectively.<br>Compared to last period both PRODUCE and BWS has done worst."}
]
  });
ReportData.insert(  {
    inserteddate: new Date(),
    reporttype: "KPITree",
    location: "UK",
    period: 7,    
    market: "Tesco",
    header: "KPI Chart",    
    PERIOD_NO:"2014P07",
    COUNTRY:"UK",
    PERIOD_GROUP:"PERIOD 201431",
    EPOS_SALES_TY:"£3550M",
    CC_SALES_TY:"£2431M",
    CC_CUSTOMERS_TY:"14M",
    CC_SPV_TY:"£25",
    CC_UPV_TY:15,
    CC_SPU_TY:"£1.7",
    CC_SPC_TY:"£172",
    CC_VPC_TY:7,
    EPOS_SALES_YOY:"-5%",
    CC_SALES_YOY:"-6.7%",
    CC_CUSTOMERS_YOY:"-1.4%",
    CC_SPV_YOY:"-4.1%",
    CC_UPV_YOY:"-3.9%",
    CC_SPU_YOY:"-0.2%",
    CC_SPC_YOY:"-5.4%",
    CC_VPC_YOY:"-1.3%",
    EPOS_SALES_CONTRIB:"-£188M",
    CC_SALES_CONTRIB:"-£174M",
    CC_CUSTOMERS_CONTRIB:"-£35M",
    CC_SPV_CONTRIB:"-£106M",
    CC_UPV_CONTRIB:"-£100M",
    CC_SPU_CONTRIB:"-£6M",
    CC_SPC_CONTRIB:"-£139M",
    CC_VPC_CONTRIB:"-£33M",
    NON_CC_TY:"£1119M",
    NON_CC_YOY:"-1.2%",
    NON_CC_CONTRIB:"-£13M",
narrations: [
    {header: "How did Tesco perform last period?", paragraph: "Total Sales has decreased by (6.1%) vs last year in 2014P06.<br>We have observed similar performance compared to last period.<br>Non Clubcard Sales declined by (2%) in 2014P06 which also contributed towards the overall decline.<br>Clubcard Sales in 2014P06 has deccreased by (7.9%) vs last year.<br>decline in Units per Basket is the biggest driver of underformance in 2014P06.<br>In 2014P06 we also saw decline in Visit per Customer.<br>However we have also observed growth in Average Price per Unit."},
    {header: "Which Customer groups influenced the change the most?", paragraph: "UP-MARKET customers sales declined by (6.8%) which contributed most to the overall sales decline. The decline in sales from UP-MARKET customers is mainly due to decrease in Units per Basket vs last year.<br>However MID MARKET Customers has shown positive growth of (8.5%)."},
    {header: "Which Store groups were impacted the most?", paragraph: "Biggest decline in Clubcard Sales came from EXTRA stores of (8.4%) which is mostly attributed to decline in Units per Basket.<br>However EXPRESS stores has shown positive growth of (6.4%)."},
    {header: "Which Categories were impacted the most?", paragraph: "PRODUCE and MFPE saw the largest Clubcard Sales decline at (13.4%) and (10.4%) driven by decline in Average Price per Unit and Customer penetration respectively.<br>Compared to last period both PRODUCE and MFPE has done worst."}
]
  });
ReportData.insert(  {
    inserteddate: new Date(),
    reporttype: "KPITree",
    location: "UK",
    period: 8,    
    market: "Tesco",
    header: "KPI Chart",    
    PERIOD_NO:"2014P08",
    COUNTRY:"UK",
    PERIOD_GROUP:"PERIOD 201435",
    EPOS_SALES_TY:"£2837M",
    CC_SALES_TY:"£1940M",
    CC_CUSTOMERS_TY:"13M",
    CC_SPV_TY:"£25",
    CC_UPV_TY:15,
    CC_SPU_TY:"£1.7",
    CC_SPC_TY:"£144",
    CC_VPC_TY:6,
    EPOS_SALES_YOY:"-3.9%",
    CC_SALES_YOY:"-5.9%",
    CC_CUSTOMERS_YOY:"-1.2%",
    CC_SPV_YOY:"-4.4%",
    CC_UPV_YOY:"-3.7%",
    CC_SPU_YOY:"-0.7%",
    CC_SPC_YOY:"-4.7%",
    CC_VPC_YOY:"-0.4%",
    EPOS_SALES_CONTRIB:"-£114M",
    CC_SALES_CONTRIB:"-£121M",
    CC_CUSTOMERS_CONTRIB:"-£25M",
    CC_SPV_CONTRIB:"-£89M",
    CC_UPV_CONTRIB:"-£75M",
    CC_SPU_CONTRIB:"-£15M",
    CC_SPC_CONTRIB:"-£96M",
    CC_VPC_CONTRIB:"-£7M",
    NON_CC_TY:"£896M",
    NON_CC_YOY:"0.8%",
    NON_CC_CONTRIB:"£7M",
narrations: [
    {header: "How did Tesco perform last period?", paragraph: "Total Sales has decreased by (5%) vs last year in 2014P07.<br>However we have seen better performance in 2014P07 compared to last period.<br>Non Clubcard Sales declined by (1.2%) in 2014P07 which also contributed towards the overall decline.<br>Clubcard Sales in 2014P07 has deccreased by (6.7%) vs last year.<br>decline in Units per Basket is the biggest driver of underformance in 2014P07.<br>In 2014P07 we also saw decline in Visit per Customer."},
    {header: "Which Customer groups influenced the change the most?", paragraph: "LESS AFFLUENT customers sales declined by (4.8%) which contributed most to the overall sales decline. The decline in sales from LESS AFFLUENT customers is mainly due to decrease in Units per Basket vs last year.<br>However MID MARKET Customers has shown positive growth of (7.8%)."},
    {header: "Which Store groups were impacted the most?", paragraph: "Biggest decline in Clubcard Sales came from METRO stores of (8.8%) which is mostly attributed to decline in Total Tesco Shoppers.<br>However EXPRESS stores has shown positive growth of (2.9%)."},
    {header: "Which Categories were impacted the most?", paragraph: "MFPE and PRODUCE saw the largest Clubcard Sales decline at (11.7%) and (11.5%) driven by decline in Average Price per Unit and Average Price per Unit respectively.<br>Compared to last period PRODUCE has seen improved performance however MFPE has done worst."}
]
  });
ReportData.insert(  {
    inserteddate: new Date(),
    reporttype: "KPITree",
    location: "UK",
    period: 9,    
    market: "Tesco",
    header: "KPI Chart",    
    PERIOD_NO:"2014P09",
    COUNTRY:"UK",
    PERIOD_GROUP:"PERIOD 201439",
    EPOS_SALES_TY:"£3050M",
    CC_SALES_TY:"£2129M",
    CC_CUSTOMERS_TY:"14M",
    CC_SPV_TY:"£26",
    CC_UPV_TY:15,
    CC_SPU_TY:"£1.7",
    CC_SPC_TY:"£155",
    CC_VPC_TY:6,
    EPOS_SALES_YOY:"-4.2%",
    CC_SALES_YOY:"-6.2%",
    CC_CUSTOMERS_YOY:"-1.3%",
    CC_SPV_YOY:"-4.7%",
    CC_UPV_YOY:"-4%",
    CC_SPU_YOY:"-0.7%",
    CC_SPC_YOY:"-5%",
    CC_VPC_YOY:"-0.4%",
    EPOS_SALES_CONTRIB:"-£133M",
    CC_SALES_CONTRIB:"-£142M",
    CC_CUSTOMERS_CONTRIB:"-£28M",
    CC_SPV_CONTRIB:"-£106M",
    CC_UPV_CONTRIB:"-£90M",
    CC_SPU_CONTRIB:"-£16M",
    CC_SPC_CONTRIB:"-£114M",
    CC_VPC_CONTRIB:"-£8M",
    NON_CC_TY:"£920M",
    NON_CC_YOY:"1%",
    NON_CC_CONTRIB:"£9M",
narrations: [
    {header: "How did Tesco perform last period?", paragraph: "Total Sales has decreased by (3.9%) vs last year in 2014P08.<br>However we have seen better performance in 2014P08 compared to last period.<br>Non Clubcard Sales grew by 0.8% in 2014P08 indicating that customers are swiping less often vs last year.<br>Clubcard Sales in 2014P08 has deccreased by (5.9%) vs last year.<br>decline in Units per Basket is the biggest driver of underformance in 2014P08.<br>In 2014P08 we also saw decline in Average Price per Unit."},
    {header: "Which Customer groups influenced the change the most?", paragraph: "LESS AFFLUENT customers sales declined by (3.9%) which contributed most to the overall sales decline. The decline in sales from LESS AFFLUENT customers is mainly due to decrease in Units per Basket vs last year.<br>However UP-MARKET Customers has shown positive growth of (6.8%)."},
    {header: "Which Store groups were impacted the most?", paragraph: "Biggest decline in Clubcard Sales came from METRO stores of (8.3%) which is mostly attributed to decline in Total Tesco Shoppers.<br>However EXPRESS stores has shown positive growth of (1.8%)."},
    {header: "Which Categories were impacted the most?", paragraph: "MFPE and PRODUCE saw the largest Clubcard Sales decline at (9.7%) and (9%) driven by decline in Average Price per Unit and Average Price per Unit respectively."}
]
  });
ReportData.insert(  {
    inserteddate: new Date(),
    reporttype: "KPITree",
    location: "UK",
    period: 10,    
    market: "Tesco",
    header: "KPI Chart",
    PERIOD_NO:"2014P10",
    COUNTRY:"UK",
    PERIOD_GROUP:"PERIOD 201444",
    EPOS_SALES_TY:"£4376M",
    CC_SALES_TY:"£3073M",
    CC_CUSTOMERS_TY:"15M",
    CC_SPV_TY:"£30",
    CC_UPV_TY:15,
    CC_SPU_TY:"£1.9",
    CC_SPC_TY:"£212",
    CC_VPC_TY:7,
    EPOS_SALES_YOY:"-0.8%",
    CC_SALES_YOY:"-2.4%",
    CC_CUSTOMERS_YOY:"-0.5%",
    CC_SPV_YOY:"-3.3%",
    CC_UPV_YOY:"-3.1%",
    CC_SPU_YOY:"-0.3%",
    CC_SPC_YOY:"-1.9%",
    CC_VPC_YOY:"1.5%",
    EPOS_SALES_CONTRIB:"-£33M",
    CC_SALES_CONTRIB:"-£74M",
    CC_CUSTOMERS_CONTRIB:"-£15M",
    CC_SPV_CONTRIB:"-£106M",
    CC_UPV_CONTRIB:"-£98M",
    CC_SPU_CONTRIB:"-£8M",
    CC_SPC_CONTRIB:"-£59M",
    CC_VPC_CONTRIB:"£47M",
    NON_CC_TY:"£1302M",
    NON_CC_YOY:"3.3%",
    NON_CC_CONTRIB:"£41M",
narrations: [
    {header: "How did Tesco perform last period?", paragraph: "Total Sales has decreased by (4.2%) vs last year in 2014P09.<br>We have observed similar performance compared to last period.<br>Non Clubcard Sales grew by 1% in 2014P09 indicating that customers are swiping less often vs last year.<br>Clubcard Sales in 2014P09 has deccreased by (6.2%) vs last year.<br>decline in Units per Basket is the biggest driver of underformance in 2014P09.<br>In 2014P09 we also saw decline in Average Price per Unit."},
    {header: "Which Customer groups influenced the change the most?", paragraph: "LESS AFFLUENT customers sales declined by (4.4%) which contributed most to the overall sales decline. The decline in sales from LESS AFFLUENT customers is mainly due to decrease in Units per Basket vs last year.<br>However MID MARKET Customers has shown positive growth of (7.4%)."},
    {header: "Which Store groups were impacted the most?", paragraph: "Biggest decline in Clubcard Sales came from METRO stores of (8.1%) which is mostly attributed to decline in Total Tesco Shoppers.<br>However EXPRESS stores has shown positive growth of (3.3%)."},
    {header: "Which Categories were impacted the most?", paragraph: "MFPE and DAIRY saw the largest Clubcard Sales decline at (9.7%) and (9.4%) driven by decline in Average Price per Unit and Units per Basket respectively.<br>Compared to last period both MFPE and DAIRY has done worst.<br>PRODUCE which observed the biggest price deflation has shown encouraging signs of increased Visits per customer and items per basket."}
]
  });
ReportData.insert(  {
    inserteddate: new Date(),
    reporttype: "KPITree",
    location: "UK",
    period: 11,    
    market: "Tesco",
    header: "KPI Chart",    
    PERIOD_NO:"2014P11",
    COUNTRY:"UK",
    PERIOD_GROUP:"PERIOD 201448",
    EPOS_SALES_TY:"£2735M",
    CC_SALES_TY:"£1876M",
    CC_CUSTOMERS_TY:"13M",
    CC_SPV_TY:"£25",
    CC_UPV_TY:15,
    CC_SPU_TY:"£1.6",
    CC_SPC_TY:"£141",
    CC_VPC_TY:6,
    EPOS_SALES_YOY:"-1.6%",
    CC_SALES_YOY:"-3.5%",
    CC_CUSTOMERS_YOY:"-1.2%",
    CC_SPV_YOY:"-2.7%",
    CC_UPV_YOY:"-1.4%",
    CC_SPU_YOY:"-1.3%",
    CC_SPC_YOY:"-2.3%",
    CC_VPC_YOY:"0.4%",
    EPOS_SALES_CONTRIB:"-£45M",
    CC_SALES_CONTRIB:"-£68M",
    CC_CUSTOMERS_CONTRIB:"-£23M",
    CC_SPV_CONTRIB:"-£52M",
    CC_UPV_CONTRIB:"-£26M",
    CC_SPU_CONTRIB:"-£26M",
    CC_SPC_CONTRIB:"-£45M",
    CC_VPC_CONTRIB:"£7M",
    NON_CC_TY:"£859M",
    NON_CC_YOY:"2.8%",
    NON_CC_CONTRIB:"£23M",
narrations: [
    {header: "How did Tesco perform last period?", paragraph: "Total Sales has decreased by (0.8%) vs last year in 2014P10.<br>However we have seen better performance in 2014P10 compared to last period.<br>Non Clubcard Sales grew by 3.3% in 2014P10 indicating that customers are swiping less often vs last year.<br>Clubcard Sales in 2014P10 has deccreased by (2.4%) vs last year.<br>decline in Units per Basket is the biggest driver of underformance in 2014P10.<br>In 2014P10 we also saw decline in Average Price per Unit.<br>However we have also observed growth in Visit per Customer."},
    {header: "Which Customer groups influenced the change the most?", paragraph: "LESS AFFLUENT customers sales declined by (1.2%) which contributed most to the overall sales decline. The decline in sales from LESS AFFLUENT customers is mainly due to decrease in Units per Basket vs last year.<br>However UP-MARKET Customers has shown positive growth of (3.4%)."},
    {header: "Which Store groups were impacted the most?", paragraph: "Biggest decline in Clubcard Sales came from METRO stores of (4%) which is mostly attributed to decline in Total Tesco Shoppers.<br>However EXPRESS stores has shown positive growth of 1.3%."},
    {header: "Which Categories were impacted the most?", paragraph: "DAIRY and PRODUCE saw the largest Clubcard Sales decline at (6.5%) and (6.5%) driven by decline in Units per Basket and Average Price per Unit respectively.<br>PRODUCE which observed the biggest price deflation has shown encouraging signs of increased Visits per customer and items per basket."}
]
  });

}